version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/BoozeBetter
hooks:
  BeforeInstall:
    - location: scripts/setup_env.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/migrate_db.sh
    - location: scripts/build_react.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
