version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/BoozeBetter
permissions:
  - object: /var/www/BoozeBetter
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 644
permissions:
  - object: /var/www/
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    type:
      - directory

hooks:
  BeforeInstall:
    - location: scripts/setup_env.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/migrate_db.sh
    - location: scripts/build_react.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: ec2-user
